language: node_js
node_js:
  - 10
script: scripts/ci-cache.sh
branches:
  only:
  - test-travis

deploy:
  provider: pages
  verbose: true
  committer_from_gh: true
  target_branch: test-travis-deploy
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: test-travis
